### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hacakirdogan** [marianfoo/ui5-cc-spreadsheetimporter#332]
### OData Version

None

### Draft

Yes

### Scenario

Freestyle

### UI5 Spreadsheet Component

v0_22_0

### What happened?

Hello Marian,
I created a new freestyle app and tried to use the spreadsheet importer component and I faced the following error. What can be the problem? I checked the versions. You can review my codes [here](https://github.com/hacakirdogan/Fiori-Library/tree/main/excelimport).
Thanks.

<img width="410" alt="image" src="https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/55239793/98f6241b-6593-42fe-9f37-dab0c0cd88ed">

### Relevant log output

```shell
Uncaught (in promise) ModuleError: failed to load 'cc/spreadsheetimporter/button/v0_10_0/SpreadsheetUpload.js' from ../thirdparty/customControl/spreadsheetImporterButton/v0_10_0/SpreadsheetUpload.js: script load error
    at se (http://localhost:8080/resources/sap-ui-core.js:10:7148)
    at ne.failWith (http://localhost:8080/resources/sap-ui-core.js:10:4989)
    at HTMLScriptElement.i (http://localhost:8080/resources/sap-ui-core.js:10:10946)
Caused by: Error: script load error
    at HTMLScriptElement.i (http://localhost:8080/resources/sap-ui-core.js:10:10988)
```

### Spreadsheet Component Init

```js
"scripts": {
    "start": "fiori run --open \"test/flpSandbox.html?sap-ui-xx-viewCache=false#excelimport-display\"",
    "start-local": "fiori run --config ./ui5-local.yaml --open \"test/flpSandbox.html?sap-ui-xx-viewCache=false#excelimport-display\"",
    "build": "ui5 build --config=ui5.yaml --clean-dest --dest dist",
    "deploy": "fiori verify",
    "deploy-config": "fiori add deploy-config",
    "start-noflp": "fiori run --open \"index.html?sap-ui-xx-viewCache=false\"",
    "start-variants-management": "fiori run --open \"preview.html?sap-ui-xx-viewCache=false&fiori-tools-rta-mode=true&sap-ui-rta-skip-flex-validation=true#preview-app\"",
    "unit-tests": "fiori run --open 'test/unit/unitTests.qunit.html'",
    "int-tests": "fiori run --open 'test/integration/opaTests.qunit.html'"
  },
```

### Manifest

```json
"componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v0_22_0"
      }
    },
    "resourceRoots": {
      "cc.spreadsheetimporter.v0_22_0": "./thirdparty/customControl/spreadsheetImporter/v0_22_0",
      "cc.spreadsheetimporter.button.v0_10_0": "./thirdparty/customControl/spreadsheetImporterButton/v0_10_0"
    },
```

**Comment by marianfoo** [comment]
Thanks for providing me the code. That made it easier to investigate.

Problem is described [here](https://docs.spreadsheet-importer.com/pages/GettingStarted/#setup-decentralized-deployment) in step 2 in the docs:

>Add to your package.json:
ℹ This step is not necessary from UI5 Tooling V3
>"ui5": {
> "dependencies": [
>    //...
>    "ui5-cc-spreadsheetimporter"
>    //...
>  ]
> }

Because you not using UI5 Tooling V3 you would have to add that to the ui5 dependencies in the `package.json`.  
I would recommend to update the Tooling to V3.  
I created a Pull Request to fix this: https://github.com/marianfoo/Fiori-Library/pull/1

**Comment by hacakirdogan** [comment]
Finally, thank you very much. I was always looking at the "dependencies" above. How did I miss the following "dependencies"?

**Comment by marianfoo** [comment]
No worries, easy to overlook.
Happy that it works :)
