### ISSUE TITLE
[Bug]: Use labels instead of technical names in preview

### ISSUE THREAD

**Issue by zinserjan** [marianfoo/ui5-cc-spreadsheetimporter#357]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements Object Page

### UI5 Spreadsheet Component

v0_25_2

### What happened?

Data preview dialog shows technical names as column titles instead of user friendly names.

It's also reproducible in the demo:
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/8046231/874ec55a-cc20-429b-8a89-6ea352b90e74)

For example:
- `buyer` should be `Customer`
- `currency_code` should be `Currency`
- etc.

### Relevant log output

```shell
-
```

### Spreadsheet Component Init

```js
-
```

### Manifest

```json
-
```

**Comment by marianfoo** [comment]
valid point, will have a look at this
Thanks!

**Comment by marianfoo** [comment]
fixed with version 0.25.3
