### ISSUE TITLE
[Bug]: new Event requestCompleted not integrated in all places

### ISSUE THREAD

**Issue by MARCxGAMBIT** [marianfoo/ui5-cc-spreadsheetimporter#388]
### OData Version

OData V2

### Draft

No

### Scenario

Fiori Elements, Object Page

### UI5 Spreadsheet Component

0.28.0

### What happened?

The new event is not attached.

### Relevant log output

```shell
?
```

### Spreadsheet Component Init

```js
?
```

**Comment by MARCxGAMBIT** [comment]
I think I have fixed this in https://github.com/marianfoo/ui5-cc-spreadsheetimporter/pull/389

**Comment by marianfoo** [comment]
worked for me in my samples app, how did you use this event?

**Comment by marianfoo** [comment]
> worked for me in my samples app, how did you use this event?

ah, probably with the ComponentContainer, right?

**Comment by MARCxGAMBIT** [comment]
tbh I was debugging the code because of a different issue and just noticed that the eventMethodMap was containing all events except for the new one.

**Comment by marianfoo** [comment]
Cheers for that. If you have more questions or findings feel free to contact me.
