### ISSUE TITLE
[Bug]: Possible error when running in standalone without columns

### ISSUE THREAD

**Issue by MARCxGAMBIT** [marianfoo/ui5-cc-spreadsheetimporter#391]
### OData Version

OData V2

### Draft

Yes

### Scenario

Fiori Elements

### UI5 Spreadsheet Component

0.28.0

### What happened?

When running the component in standaline and not defining columns the Dialog doesn't open.

https://github.com/marianfoo/ui5-cc-spreadsheetimporter/blob/main/packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts#L82

The error message is that `setVisible` cannot be called on `undefined`.

So I did some debugging and yes, `this.spreadsheetUploadDialog.getSubHeader() ` is `null`. This is also the case in your livedemo (but since it's not standalone `getSubHeader()` will not be called).

I didn't find any `subHeader` aggregation in the dialog's fragment, only a `customHeader`. In fact I didn't find `subHeader` anywhere except in the above mentioned link.

### Relevant log output

```shell
`setVisible` cannot be called on `undefined`
```

### Spreadsheet Component Init

```js
this.spreadsheetUpload = await this.getView().getController().getOwnerComponent().createComponent({
                usage: "spreadsheetImporter",
                async: true,
                componentData: {
                    context: this,
                    odataType: "cds_zccm_conv_proj_sd.ReadinessTmpType",
                    standalone: true
                }
            });
```

**Comment by marianfoo** [comment]
The standalone mode is intended for when no binding is available.
I think what you want is that no create request is sent right?

You would do it like this:  

```js
this.spreadsheetUpload.attachUploadButtonPress(function (oEvent) {
				const model = this.getModel("tableData");
				model.setData(oEvent.getParameter("rawData"));
				oEvent.preventDefault();
			}, this);
```

The `oEvent.preventDefault();` prevents for any action happening after this:  
https://github.com/marianfoo/ui5-cc-spreadsheetimporter/blob/51f5c042ce648707ed31a6bd0e4af6e0d4f53cb3/packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts#L182C1-L190

Here is it in the docs but the code is slightly false, need to fix it:  
https://docs.spreadsheet-importer.com/pages/Events/#event-when-the-upload-button-is-pressed

**Comment by MARCxGAMBIT** [comment]
Not sure we are on the same page. In our use case we don't need a template, the XLSX file is coming from a different app. For reasons (target entity is not visible in the frontend) we use standalone.

You have written code for exactly this use case here

https://github.com/marianfoo/ui5-cc-spreadsheetimporter/blob/main/packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts#L82

`if (this.component.getStandalone() && this.component.getColumns().length === 0) {`

but the code that is being executed when this statement is true is throwing an error because the Dialog has no subHeader.

**Comment by marianfoo** [comment]
I need more comments in my Code :)
Do you have time for a quick call? Call me at marian@marianzeis.de  
I think this is more efficient

**Comment by marianfoo** [comment]
Thanks again for the call:  

In standalone mode the button to download the template should be hidden.  Probably there was a change in the XML View so the code breaks when `standaloneMode: true` and `columns` not defined
