### ISSUE TITLE
[Bug]: Documentation: Build for decentralized deployment

### ISSUE THREAD

**Issue by MARCxGAMBIT** [marianfoo/ui5-cc-spreadsheetimporter#392]
### OData Version

no OData Service related

### Draft

not relevant

### Scenario

Fiori Elements

### UI5 Spreadsheet Component

0.28.0

### What happened?

When building the app, spreadsheet component is not included in the dist folder.

The doc says you don't need to add `--all` to your build script but it seems like you have to add it, even when using @ui5/cli v 3.7.0.

I checked the doc of @ui5/cli 

https://sap.github.io/ui5-tooling/v3/updates/migrate-v3/#always-building-required-dependencies

and it seems like the `-all` flag used to mean something different in v2

https://sap.github.io/ui5-tooling/v2/pages/CLI/#ui5-build

> `-a, --all` Include all project dependencies into build process

(this is now activated by default in v3)

https://sap.github.io/ui5-tooling/v3/pages/CLI/#ui5-build

> `-a, --include-all-dependencies, --all` Include all dependencies in the build result

With the `--all` flag the `dist` now contains a `thirdparty` folder with the sources of the component.

### Relevant log output

```shell
?
```

### Spreadsheet Component Init

```js
?
```

**Comment by MARCxGAMBIT** [comment]
Not sure what the correct documentation would be.

Use `--all` in cli v3 and use `--include-dependency "*"` in cli v2?

**Comment by marianfoo** [comment]
Somehow I thought this was already enabled as default in v3 but apparently it is still necessary.
Actually V3 should be default anyway.
But your suggestion is good, I think I'll write it that way.

**Comment by aboccassiniavvale** [comment]
Hello everyone,

some SAPUI5 generators use the 'ui5-task-zipper' component to zip the content and then deploy it.
In this case, you must remember to add "ui5-cc-spreadsheetimporter" among the dependencies to be included in your ui5.yaml
Following an example:

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/144323043/401b4efc-e5af-4ce6-93de-58906c5771c8)

Thanks & Regards
Alessandro
