### ISSUE TITLE
New Request: add XLSM fileformat (Microsoft Excel Macro-Enabled)

### ISSUE THREAD

**Issue by aboccassiniavvale** [marianfoo/ui5-cc-spreadsheetimporter#394]
Hi,

is it possible to add the "XLSM" file type to the supported type on sap.ui.unified.FileUploader?
I tried to force manually this extension and it seems to work fine.

If not, is there a way to dynamically add this extension in the sap.ui.unified.FileUploader?

Thanks & Regards
Alessandro

**Comment by marianfoo** [comment]
available with version `0.28.1`
