### ISSUE TITLE
[Bug]: No Entity Set detected in yo generator

### ISSUE THREAD

**Issue by andresj6** [marianfoo/ui5-cc-spreadsheetimporter#400]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements

### UI5 Spreadsheet Component

cc.spreadsheetimporter.v0_28_1

### What happened?

Hi,

I am trying to add the component using the yo generator. But in the step where I have to select the entity Set no one appears and I can't continue.
<img width="294" alt="image" src="https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/7b46b49a-305c-4f1e-b90c-6bb74eab27ae">

### Relevant log output

```shell
No log output because it is not generated.
```

### Spreadsheet Component Init

```js
No init because it is not generated.
```

### Manifest

```json
"resourceRoots": {
      "cc.spreadsheetimporter.v0_28_1": "./thirdparty/customControl/spreadsheetImporter/v0_28_1"
    },
    "componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v0_28_1"
      }
```

**Comment by marianfoo** [comment]
Thank you for the bug report.

The generator has long been neglected.  I am currently looking for a better solution, so I will not improve that for now.
It's best to use Guides Developments with the Fiori tools and the docs, then you'll reach your goal pretty quickly.

**Comment by andresj6** [comment]
Hello Marian,

No problem, I will add it using Fiori tools then.
Two doubts more (I don't know if you can answer them here or do you want me
to open other issue):
1. When I try to deploy I get this error:
[image: image.png]
It says that the file
fich.thirdparty/customControl/spreadsheetImporter/v0_28 is unknown. ¿Is it
related with the version used?
I have this one in the manifest:
[image: imagen]
2. When in the uploaded Excel is there a row with the same key of a
existing register an error occur because it tries to create a new register:
[image: imagen]
¿Could it be possible that if it finds a register already existing with the
same key it gets modified with the data of the Excel (like a massive
modify)?

Best regards,
Andrés

**Comment by marianfoo** [comment]
Please create new issues, especially because the images are missing and the formatting is weird when you answer with email
