### ISSUE TITLE
[Enhancement]:  Use the excel to modify massively registers

### ISSUE THREAD

**Issue by andresj6** [marianfoo/ui5-cc-spreadsheetimporter#402]
### OData Version

no OData Service related

### Draft

not relevant

### Scenario

Fiori Elements, List Report

### UI5 Spreadsheet Component

v0_28_1

### What happened?

 When in the uploaded Excel is there a row with the same key of a existing register an error occur because it tries to create a new register:
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/d46f2234-9ff5-48ac-a7b9-4fdd71d5f044)
¿Could it be possible that if it finds a register already existing with the same key it gets modified with the data of the Excel (like a massive modify)?

### Relevant log output

```shell
No relevant
```

### Spreadsheet Component Init

```js
No relevant
```

**Comment by marianfoo** [comment]
Update will be only available in the Pro Version.

But you can check in a event if there keys already available and change that.
