### ISSUE TITLE
[Bug]: Odata V4 service generated using RAP is not showing me the entity when I run the yo generator

### ISSUE THREAD

**Issue by Raghu9t2** [marianfoo/ui5-cc-spreadsheetimporter#420]
### OData Version

OData V4

### Draft

Yes

### Scenario

List Report

### UI5 Spreadsheet Component

0.29.0

### What happened?

I have a odata v4 service created using the RAP generator for a custom table

The intention here is to upload the data to the table via an excel upload functionality available in a list report application and view them in the list report app.

when I use the BAS and created a list report app from the template providing the service details and try to setup the import spreadsheet via command line using yo generator at the step choose entity it shows me blank. however I have an entity available for the list report.

Attached the screenshot of the CLI with no entity and metadata with the entity information

<img width="452" alt="CLI" src="https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/47977436/f5b25279-0501-4f75-a7a6-012517a83b25">
<img width="663" alt="metadata_xml" src="https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/47977436/6a9e5c8b-0faf-4ccb-8c02-919677131007">

### Relevant log output

```shell
Attached the log in above section
```

### Spreadsheet Component Init

```js
"sap.ui5": {
        "flexEnabled": true,
        "dependencies": {
            "minUI5Version": "1.114.9",
            "libs": {
                "sap.m": {},
                "sap.ui.core": {},
                "sap.ushell": {},
                "sap.fe.templates": {}
            }
        },
        "componentUsages": {
            "spreadsheetImporter": {
                "name": "cc.spreadsheetimporter.v0_29_0"
            }
        },
        "resourceRoots": {
            "cc.spreadsheetimporter.v0_29_0": "./thirdparty/customControl/spreadsheetImporter/v0_29_0"
        },
        "contentDensities": {
            "compact": true,
            "cozy": true
        },
        "models": {
            "i18n": {
                "type": "sap.ui.model.resource.ResourceModel",
                "settings": {
                    "bundleName": "com.sap.zeu.zexcelupload.i18n.i18n"
                }
            },
            "": {
                "dataSource": "mainService",
                "preload": true,
                "settings": {
                    "synchronizationMode": "None",
                    "operationMode": "Server",
                    "autoExpandSelect": true,
                    "earlyRequests": true
                }
            },
            "@i18n": {
                "type": "sap.ui.model.resource.ResourceModel",
                "uri": "i18n/i18n.properties"
            }
        },
        "resources": {
            "css": []
        },
        "routing": {
            "routes": [
                {
                    "pattern": ":?query:",
                    "name": "ZC_MFG_SNO_COLList",
.....
```

**Comment by marianfoo** [comment]
Hi @Raghu9t2 
thank you for your bug report.  

The development for the generator is currently paused as I am looking for a better solution.
Since the integration is very simple, I think it can also go without a generator for now.
