### ISSUE TITLE
npm install npm install ui5-cc-spreadsheetimporter not working in BAS terminal ( BTP Trial Account )

### ISSUE THREAD

**Issue by Aashish28** [marianfoo/ui5-cc-spreadsheetimporter#458]
Hello,
npm install npm install ui5-cc-spreadsheetimporter not working in BAS terminal ( BTP Trial Account ), is it something new repository issue v0.31 ?
See screenshot, Can you please help here ?

![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/5344419/b98fb2db-19a4-4245-b14b-9117a10b7f85)

Regards,
Ashish

**Comment by marianfoo** [comment]
Hi,
please use the template for these issuse.
Also, i dont see a problem in your screenshot.

**Comment by Aashish28** [comment]
Thanks for reply ? 
Can you please guide me which template ? 
Regarding screenshot - its stuck and not downloading your npm package at all.

**Comment by marianfoo** [comment]
it works on my side, i can install the npm package and download the sheetjs package.  
That is a BAS issue.
